sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - mkdir -p $HOME/.yarn_cache
  - cp -f yarn.lock $HOME/.yarn_cache/yarn.lock
cache:
  cocoapods: true
  yarn: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.yarn_cache
    - node_modules

jobs:
  include:
  - stage: first
    env: JOB=lint
    language: node_js
    node_js: 11
    install:
      - travis_retry yarn
      - travis_retry yarn global add @commitlint/travis-cli
    script:
      - commitlint-travis
      - yarn lint
      - yarn lerna run prepare --scope=@admob-plus/core --scope=cordova-admob-plus
      - pushd packages/cli
      - yarn prepack
      - popd
      - pushd examples/ionic-angular
      - yarn lint
      - popd
  - stage: first
    env: JOB=deploy-docs
    if: branch = master AND type != pull_request
    language: node_js
    node_js: 11
    install:
      - travis_retry yarn
    after_success:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - pushd website
      - travis_retry yarn
      - GIT_USER="${GH_NAME}" yarn publish-gh-pages
      - popd
  - stage: test
    env: PLATFORM=ios-12.0
    os: osx
    osx_image: xcode10
  - env:
      - PLATFORM=android-5.1
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=22
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools
        - build-tools-26.0.2
        - android-$ANDROID_API_LEVEL
        - android-$ANDROID_API_LEVEL
        - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
  - env:
      - PLATFORM=android-4.4
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=19
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools
        - build-tools-27.0.3
        - android-$ANDROID_API_LEVEL
        - android-$ANDROID_API_LEVEL
        - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL

before_install:
  - nvm install 11
  - test -f $HOME/.yarn_cache/yarn.lock && cp $HOME/.yarn_cache/yarn.lock yarn.lock || true
  - travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [[ "$PLATFORM" =~ android ]]; then android list sdk --extended --no-ui --all; fi
  - if [[ "$PLATFORM" =~ android ]]; then android list targets; fi
  - if [[ "$PLATFORM" =~ ios ]]; then pod --version; fi

install:
  - travis_retry yarn
  - if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-22,android-23,android-24,android-25,android-26,android-27,android-28; fi
  - if [[ "$PLATFORM" =~ android ]]; then echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI; fi
  - if [[ "$PLATFORM" =~ ios ]]; then pod repo update; fi
  - if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
  - yarn lerna run prepare

script:
  - yarn test
  - if [[ "$PLATFORM" =~ android ]]; then yarn test-android; fi
  - if [[ "$PLATFORM" =~ ios ]]; then yarn test-ios; fi
  - if [[ "$PLATFORM" =~ ios ]]; then pushd packages/cordova/src/ios && swiftlint && popd; fi
