verbose = true

max-concurrency = 8

exclude = [
  "adlic.rjfun.com",
  "https://github.com/admob-plus/admob-plus/blob/",
  "https://github.com/admob-plus/admob-plus/edit/",
  "https://github.com/admob-plus/admob-plus/tree/",
  "https://npmjs.org/package/admob-plus-cordova-native",
  "https://admob-plus.github.io/docs/cordova/ads/native",
  "admob-plus.github.io",
]
